# From: http://allandenot.com/devops/2015/01/31/provisioning-ec2-hosts-with-ansible.html
---
  # We need the vpc playbook for creating the security group
  - include: playbooks/create-vpc.yml
  - include: playbooks/instance-sg.yml
  - include: playbooks/app-subnet.yml

  - debug: msg='Tags = {"Project":"{{aws_tag_Project}}","Role":"App","Use":"{{aws_service_level}}","ResponsibleParty":"{{aws_tag_ResponsibleParty}}"{{ tag_hash_values }}}'
  - name: Provision ec2 box
    local_action:
      module: ec2
      key_name: "{{ aws_keypair }}"
      group_id: "{{ ec2_sg.group_id }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_base_image }}"
      vpc_subnet_id: "{{ [ app_subnet1.subnet.id, app_subnet2.subnet.id ]|random }}"
      region: "{{ aws_region }}"
      instance_tags: '{"Project":"{{aws_tag_Project}}","Role":"App","Use":"{{aws_service_level}}","ResponsibleParty":"{{aws_tag_ResponsibleParty}}"{{ tag_hash_values }}}'
      assign_public_ip: yes
      wait: true
      count: 1
      volumes:
      - device_name: /dev/sda1
        device_type: gp2
        volume_size: "{{ ec2_volume_size }}"
        delete_on_termination: true
    register: ec2

  - debug: var=item
    with_items: ec2.instances

  - add_host: name={{ item.public_ip }} >
              groups=tag_Role_App,tag_Use_{{aws_service_level}}
              ec2_region={{aws_region}}
              ec2_tag_Project={{aws_tag_Project}}
              ec2_tag_Role=App
              ec2_tag_Use={{aws_service_level}}
              ec2_tag_ResponsibleParty={{aws_tag_ResponsibleParty}}
              ec2_ip_address={{item.public_ip}}
    with_items: ec2.instances

  - name: Wait for the instance to boot by checking ssh
    wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=600 state=started
    with_items: ec2.instances
