# Create (if needed) a vpc for the project
# Registers the VPC
---
- name: Create VPC
  local_action:
    module: ec2_vpc
    region: "{{ aws_region }}"
    internet_gateway: yes
    state: present
    cidr_block: 10.1.0.0/16
    resource_tags: '{"Project":"{{aws_tag_Project}}","Role":"VPC","Use":"{{aws_service_level}}","ResponsibleParty":"{{aws_tag_ResponsibleParty}}"}'
  register: vpc

